name: linux

on:
  push:
    branches: [ "feature/ci" ]
  pull_request:
    branches: [ "feature/ci" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - { compiler: gcc,   version: 4.9 }
          - { compiler: gcc,   version: 11 }
          - { compiler: gcc,   version: 15 }
          - { compiler: clang, version: 3.6 }
          - { compiler: clang, version: 11 }
        build_type: [ Debug, Release ]

    container:
      image: ${{ matrix.config.compiler == 'clang' && 'teeks99/clang-ubuntu' || matrix.config.compiler }}:${{ matrix.config.version }}

    name: "${{ matrix.config.compiler}} ${{ matrix.config.version }} (C++${{ matrix.config.cppstd }} ${{ matrix.config.build_type }} ${{ matrix.config.asan == 'ON' && 'ASAN' || '' }}${{ matrix.config.tsan == 'ON' && 'TSAN' || '' }})"
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update
          echo "installing dev libs"
          apt install -y cmake
          echo "installing openGL Libs"
          apt install -y libglfw3-dev libgl1-mesa-dev libegl1-mesa-dev libglu1-mesa-dev libgegl-dev libxext-dev
          echo "installing X11 libs"
          apt install -y libxcursor-dev libx11-dev libxrandr-dev libxi-dev libxinerama-dev libxfixes-dev libxrender-dev libxxf86vm-dev

      - name: Setup Compiler
        if: startsWith(matrix.cxx, 'clang')
        run: |
          compiler_version=$(echo "${{ matrix.cxx }}" | cut -d'-' -f2)
          echo "compiler_version=${compiler_version}"
          scripts/ci_setup_clang.sh "${compiler_version}"
          echo "CXXFLAGS=-stdlib=libc++" >> $GITHUB_ENV          
          echo "CC=clang-${compiler_version}" >> $GITHUB_ENV
          echo "CXX=clang++-${compiler_version}" >> $GITHUB_ENV

      - name: Create build environment
        run: |
          cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure
        working-directory: ${{runner.workspace}}/build
        env:
          CXX: ${{matrix.cxx}}
          CXXFLAGS: ${{matrix.cxxflags}}
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
                -DCMAKE_CXX_STANDARD=${{matrix.std}} \
                -DHORDE3D_BUILD_TESTS=Yes \
                -DHORDE3D_BUILD_EXAMPLES=Yes \
                $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: |
          make all -j"$(nproc)"
