name: macos

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - { cppstd: 11 }
          - { cppstd: 17 }
          - { cppstd: 20 }
        build_type: [ Debug, Release ]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          threads=`sysctl -n hw.logicalcpu`
          mkdir -p build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
            -DCMAKE_CXX_STANDARD=${{ matrix.config.cppstd }} \
            -DHORDE3D_BUILD_TESTS=Yes \
            -DHORDE3D_BUILD_EXAMPLES=Yes
          make -j $threads
          

  ios:
    runs-on: macOS-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - { abi: "arm64" }
        build_type: [ Debug ]

    name: "ios (${{ matrix.config.abi }} ${{ matrix.build_type }})"
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: |
          threads=`sysctl -n hw.logicalcpu`
          mkdir -p build && cd build
          cmake .. \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_ARCHITECTURES=${{ matrix.config.abi }} \
            -DHORDE3D_BUILD_TESTS=No \
            -DHORDE3D_BUILD_EXAMPLES=Yes \
            -DHORDE3D_FORCE_DOWNLOAD_SDL=Yes \
            -DHORDE3D_USE_GLES3=Yes \
            -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: |
          cmake --build .
          
          
